services:
  web:
    build: .
    container_name: ${ secrets.DOCKER_HUB_USERNAME }/web:${ github.sha }
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_HOST=db
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:17.6
    container_name: ${ secrets.DOCKER_HUB_USERNAME }/db:${ github.sha }
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ${ secrets.DOCKER_HUB_USERNAME }/redis:${ github.sha }
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    restart: unless-stopped

  celery:
    build: .
    container_name: ${ secrets.DOCKER_HUB_USERNAME }/celery:${ github.sha }
    command: celery -A config worker --pool=solo -l info
    depends_on:
      - redis
    env_file:
      - ./.env
    restart: unless-stopped

  celery-beat:
    build: .
    container_name: ${ secrets.DOCKER_HUB_USERNAME }/celery-beat:${ github.sha }
    command: celery -A config beat -l info
    depends_on:
      - redis
      - celery
    env_file:
      - ./.env
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
