# Generated by Django 5.2.11 on 2026-02-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
